---

version: '2.4'

services:
  authenticate:
    restart: unless-stopped
    image: basic-oauth2
    build: ../..
    environment:
      BASIC_OAUTH2_CONFIG_FILE: /etc/basic-oauth2.yaml
    ports:
      - '127.0.0.1:9096:9096'
    volumes:
      - '../../out/basic-oauth2:/bin/basic-oauth2'
      - './basic-oauth2.yaml:/etc/basic-oauth2.yaml:ro'
      - './insecure.key:/run/secrets/jwt.key:ro'
  grafana:
    restart: unless-stopped
    image: docker.io/grafana/grafana
    environment:
      GF_INSTANCE_NAME: grafana
      GF_DOMAIN: 'localhost'
      GF_ROOT_URL: http://localhost:3000/

      GF_ANALYTICS_REPORTING_ENABLED: 'false'
      GF_ANALYTICS_CHECK_FOR_UPDATES: 'false'

      GF_SECURITY_DISABLE_INITIAL_ADMIN_CREATION: 'true'
      GF_SECURITY_DISABLE_GRAVATAR: 'true'

      GF_SNAPSHOTS_EXTERNAL_ENABLED: 'false'

      GF_LOG_MODE: 'console'
      GF_LOG_LEVEL: 'debug'

      GF_USERS_ALLOW_SIGN_UP: 'false'
      GF_USERS_ALLOW_ORG_CREATE: 'false'
      GF_USERS_AUTO_ASSIGN_ORG_ROLE: 'Viewer'

      GF_AUTH_DISABLE_SIGNOUT_MENU: 'true'
      GF_AUTH_DISABLE_LOGIN_FORM: 'true'
      GF_AUTH_OAUTH_AUTO_LOGIN: 'true'

      GF_AUTH_ANONYMOUS_ENABLED: 'false'

      GF_AUTH_BASIC_ENABLED: 'false'

      GF_AUTH_GENERIC_OAUTH_ENABLED: 'true'
      GF_AUTH_GENERIC_OAUTH_CLIENT_ID: 'grafana'
      GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: 'dashboard'
      GF_AUTH_GENERIC_OAUTH_SCOPES: 'openid email'
      GF_AUTH_GENERIC_OAUTH_AUTH_URL: 'http://localhost:9096/authorize'
      GF_AUTH_GENERIC_OAUTH_TOKEN_URL: 'http://authenticate:9096/token'
      GF_AUTH_GENERIC_OAUTH_API_URL: 'http://authenticate:9096/userinfo'
      GF_AUTH_GENERIC_OAUTH_ALLOWED_DOMAINS: 'example.com'
      GF_AUTH_GENERIC_OAUTH_ALLOW_SIGN_UP: 'true'
      GF_AUTH_GENERIC_OAUTH_TLS_SKIP_VERIFY_INSECURE: 'true'
    ports:
      - '127.0.0.1:3000:3000'
    volumes:
      - 'grafana-data:/var/lib/grafana'
    depends_on:
      - authenticate

volumes:
  grafana-data: {}
