---

"${BASIC_OAUTH2_PRINCIPAL_IDENT}":
  password: "${BASIC_OAUTH2_PRINCIPAL_PASSWORD}"
  #password: "!${BASIC_OAUTH2_PRINCIPAL_PASSWORD_FILE}"
  email: "${BASIC_OAUTH2_PRINCIPAL_EMAIL}"
  email_verified: "${BASIC_OAUTH2_PRINCIPAL_EMAIL_VERIFIED}"
